config/routes.rb
Rails.application.routes.draw do
	root to: 'application#landing'

  # ReactOnRails sample route
  get 'hello_world', to: 'hello_world#index'

  # SESSION
  get '/logout', to: 'sessions#destroy'
	get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  # USER
  get '/sign_up', to: 'users#new', as: :sign_up
  post '/sign_up', to: 'users#create'

  resources :users, only: [:edit, :update]
	delete '/users/:id', to: 'users#destroy', as: :destroy_user


  # Password reset
  get '/request_password_reset/new', to: 'password_reset#request_password_reset', as: :request_password_reset
  post '/request_password_reset', to: 'password_reset#create_password_reset'
  get '/reset_password/:token', to: 'password_reset#reset_password', as: :reset_password
  patch '/reset_password', to: 'password_reset#set_new_password'

  # Admin stuff
  namespace :admin do
    get '', to: 'dashboard#index', as: :dashboard
    get '/settings', to: 'settings#edit'
    patch '/settings', to: 'settings#update'
    get '/settings/captcha_system_status', to: 'settings#captcha_system_status'


    scope '/users' do
      get '', to: 'users#index', as: :index_users
			get '/new', to: 'users#new', as: :new_user
      post '', to: 'users#create'
      delete '/:id', to: 'users#destroy', as: :delete_user
      patch '/:id/toggle_activation', to: 'users#toggle_activation', as: :toggle_activation
    end
  end          
end

app/models/admin/setting.rb
require 'validators/custom_validators'

class Admin::Setting < ActiveRecord::Base
  include CustomValidators

  validates :app_title, length: { maximum: 20 }
  validates :relay_mail_address, presence: true, email_format: true
  validates :user_activation_tokens, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :captcha_system, inclusion: { in: %w[recaptcha simple_captcha] }

  ## SANITIZE
  def self.all_settings
    self.last.attributes.except("id")
  end

  def self.captcha_systems
    %w[recaptcha simple_captcha]
  end

  Admin::Setting.create unless Admin::Setting.any?
  # spawn default values (-> schema) if no current settings available
  attributes = column_names.reject { |x| x == 'id' }
  attributes.each do |attribute|
    define_singleton_method(attribute.to_sym) do
      last.send(attribute)
    end
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminController
  before_action :init_settings, only: [:edit, :update]

  def edit
    @settings_hash = Admin::Setting.all_settings
    respond_to do |format|
			format.html
      format.json { render json: @settings_hash.to_json, status: :ok }
    end
  end

  def update
    respond_to do |format|
      if @settings.update_attributes(settings_params)
        format.html do
          flash[:success] = "Settings updated successfully!"
          redirect_to admin_settings_url
        end
        format.json { render json: @settings.to_json, status: :ok}
      else
        format.html do
          flash[:danger] = @settings.errors.full_messages.to_sentence
          render :edit
        end
        format.json { render json: @settings.errors.to_json, status: :bad_request}
			end
    end
  end

  def captcha_system_status
    respond_to do |format|
      format.json { render json: check_captcha_system(captcha_system: params[:captcha_system]).to_json, status: 200 }
    end
  end

  private

  def check_captcha_system(captcha_system:)
    case captcha_system
      when 'recaptcha'
        return recaptcha_status
      when 'simple_captcha'
        return simple_captcha_status
    end
  end

  def recaptcha_status
    if ENV['RECAPTCHA_SITE_KEY'] && ENV['RECAPTCHA_SECRET_KEY']
      { status_code: 'working', status_message: 'Captcha system working' }
    else
      { status_code: 'error', status_message: 'No valid API key' }
    end
  end

  def simple_captcha_status
    return { status_code: 'working', status_message: 'Captcha system working' }
  end

  def settings_params
    params.require(:admin_setting).permit(
        :app_title,
        :admin_email_address,
        :user_activation_tokens,
        :captcha_system,
        :app_imprint,
        :app_privacy_policy,
        :multi_color_pois,
        :default_poi_color,
        :expiry_days
    )

  end

  def init_settings
    @settings = Admin::Setting.last || Admin::Setting.create
  end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/edit.html.haml
%h1 Settings

.container
  = form_for(@settings, url: admin_settings_path) do |f|
    %ul.nav.nav-tabs
      %li.nav.active
        %a{'data-toggle' => 'tab', href: '#base'}
          Base settings
      %li.nav
        %a{'data-toggle' => 'tab', href: '#users'}
          Users
      %li.nav
        %a{'data-toggle' => 'tab', href: '#security'}
          Security

    .tab-content
      -# PUBLIC SETTINGS
      .tab-pane.active#base
        .col-xs-12
          = f.label :app_title, 'App title'
          = f.text_field :app_title, class: 'form-control', placeholder: t('.app_title')

        .col-xs-12
          = f.label :admin_email_address, 'Relay email address'
          = f.text_field :admin_email_address, class: 'form-control', placeholder: t('.admin_email_address')


      -# USER SETTINGS
      .tab-pane#users
        .col-xs-12.col-md-6.col-lg-4
          = f.label :user_activation_tokens, t('.user_activation_tokens')
          = f.number_field :user_activation_tokens, min: 0, class: 'form-control'


      -# SECURITY SETTINGS
      .tab-pane#security
        %fieldset.form-group.row
          .col-xs-12
            .label-div
              = f.label :captcha_system, 'Captcha system'
            .selection-div
              = f.collection_select :captcha_system, Admin::Setting.captcha_systems, :to_s, :humanize, class: 'form-control'
              .notification
                .icon.pull-left
                  .status-icon.spinner-icon.fa.fa-circle-o-notch.fa-spin.fa-1x.fa-fw
                  .status-icon.error-icon.fa.fa-exclamation-triangle
                  .success-icon.fa.fa-check-circle
                .status-text

    -# BUTTONS
    .spacer-row
    .row
      .col-xs-6.col-md-3
        = f.submit 'Update', class: 'btn btn-primary btn-success'
      .col-xs-6.col-md-3
        = link_to 'Back', '', class: 'btn btn-primary btn-danger back-button'