config/routes.rb
Rails.application.routes.draw do
	root to: 'application#landing'

  # ReactOnRails sample route
  get 'hello_world', to: 'hello_world#index'

  # SESSION
  get '/logout', to: 'sessions#destroy'
	get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  # USER
  get '/sign_up', to: 'users#new', as: :sign_up
  post '/sign_up', to: 'users#create'

  resources :users, only: [:edit, :update]
	delete '/users/:id', to: 'users#destroy', as: :destroy_user


  # Password reset
  get '/request_password_reset/new', to: 'password_reset#request_password_reset', as: :request_password_reset
  post '/request_password_reset', to: 'password_reset#create_password_reset'
  get '/reset_password/:token', to: 'password_reset#reset_password', as: :reset_password
  patch '/reset_password', to: 'password_reset#set_new_password'

  # Admin stuff
  namespace :admin do
    get '', to: 'dashboard#index', as: :dashboard
    get '/settings', to: 'settings#edit'
    patch '/settings', to: 'settings#update'
    get '/settings/captcha_system_status', to: 'settings#captcha_system_status'


    scope '/users' do
      get '', to: 'users#index', as: :index_users
			get '/new', to: 'users#new', as: :new_user
      post '', to: 'users#create'
      delete '/:id', to: 'users#destroy', as: :delete_user
      patch '/:id/toggle_activation', to: 'users#toggle_activation', as: :toggle_activation
    end
  end          
end

app/views/layouts/navbar/_navbar.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      = link_to Admin::Setting.app_title, root_path, class: 'navbar-brand'
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.dropdown
          %a#themes.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Dropdown Menu
            %span.caret
          %ul.dropdown-menu{"aria-labelledby" => "themes"}
            %li
              %a{:href => "#"} Default
            %li.divider
            %li
              %a{:href => "#"} Foo
            %li
              %a{:href => "#"} Bar
            %li
              %a{:href => "#"} Batz
            %li
              %a{:href => "#"} Barf
        %li
          %a{:href => "#"} Some
        %li
          %a{:href => "#"} Stuff
      %ul.nav.navbar-nav.navbar-right
        %li
          - if current_user.guest?
            = link_to 'Sign in', login_url
          - else
            = render 'layouts/navbar/user_dropdown'

app/views/layouts/navbar/_user_dropdown.html.haml
%li.dropdown
  %a#themes.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    User
    %span.caret
  %ul.dropdown-menu{"aria-labelledby" => "themes"}
    %li
      = link_to 'Preferences', edit_user_path(id: current_user.id)
    %li.divider
    %li
      = link_to 'Sign out', logout_path(id: current_user.id)